MODEL:
  META_ARCHITECTURE: "fcn16s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: 'fcn32s'
    WEIGHT: "/home/rick/Work/git/dl/fcn-scratch/checkpoints/train_fcn32s/fcn_model_13.pth"

DATASETS:
  ROOT: '/home/rick/Work/dataset/voc/VOCdevkit/VOC2012/'

SOLVER:
  MAX_EPOCHS: 8
  CHECKPOINT_PERIOD: 8

OUTPUT_DIR: "/home/rick/Work/git/dl/fcn-scratch/checkpoints/train_fcn16s"
