
MODEL:
  META_ARCHITECTURE: "fcn32s"

  BACKBONE:
    PRETRAINED: True
    WEIGHT: '/home/rick/Work/model_zoo/vgg16-397923af.pth'

  REFINEMENT:
    NAME: ''

DATASETS:
  ROOT: '/home/rick/Work/dataset/voc/VOCdevkit/VOC2012/'

SOLVER:
  MAX_EPOCHS: 13  
  CHECKPOINT_PERIOD: 13

OUTPUT_DIR: "/home/rick/Work/git/dl/fcn-scratch/checkpoints"
