
MODEL:
  META_ARCHITECTURE: "fcn8s"

  BACKBONE:
    PRETRAINED: False

  REFINEMENT:
    NAME: 'fcn16s'
    WEIGHT: "/home/rick/Work/git/dl/fcn-scratch/checkpoints/train_fcn16s/fcn_model_8.pth"

DATASETS:
  ROOT: '/home/rick/Work/dataset/voc/VOCdevkit/VOC2012/'

SOLVER:
  MAX_EPOCHS: 50
  CHECKPOINT_PERIOD: 15

OUTPUT_DIR: "/home/rick/Work/git/dl/fcn-scratch/checkpoints/train_fcn8s"
